---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Group A:
    - Jellyfin:
         icon: jellyfin.png
         description: Jellyfin is the Free Software Media System that puts you in control of managing and streaming your media. There are no strings attached, no premium licenses or features, and no hidden agendas.
         href: http://10.0.0.9:8097
         widget:
            type: jellyfin
            url: http://10.0.0.9:8097
            key: d72d56b146e245fba6bc0392815038bc


- My Second Group:
    - Portainer:
         icon: portainer.png
         description:
         href: http://10.0.0.9:9002
         widget:
            type: portainer
            url: http://10.0.0.9:9002
            env: 2
            key: ptr_xKf+wM3ga6Mu9jEkcp/vbA5jCGiXBFIDbigngo6ObrE=
    - Pi-hole:
         icon: pihole.png
         description: Pi-hole is a Linux network-level advertisement and internet tracker blocking application which acts as a DNS sinkhole, intended for use on a private network.
         href: http://10.0.0.9/admin
         widget:
            type: pihole
            url: http://10.0.0.9
            key: e498a91353c60adc42886521a508c2bd67e8b697a1c5a9076fee4a317410cabc
    - qBittorrent:
         icon:  qbittorrent.png
         description: The qBittorrent project aims to provide an open-source software alternative to µTorrent.
         href: http://10.0.0.9:1340/
         widget:
            type: qbittorrent
            url: http://10.0.0.9:1340/
            username: qbittorrent
            password: dietpi

- My Third Group:
    - Nextcloud:
        href: http://10.0.0.9/nextcloud
        description: Nextcloud is an open source, self-hosted file share and communication platform. Access and sync your files, contacts, calendars and communicate and collaborate across your devices.
        widget:
            type: nextcloud
            url: http://10.0.0.9/nextcloud
            username: admin
            password: pf38a-TwbGP-Ypjj9-ZsHWK-EgK6k
